//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Eau()
        {
            this.RelveeEaux = new HashSet<RelveeEau>();
        }
    
        public int NPolice { get; set; }
        public string Adresse { get; set; }
        public System.DateTime Date { get; set; }
        public string Tel { get; set; }
        public int NCompteur { get; set; }
        public string Reference { get; set; }
        public short Annee { get; set; }
        public Nullable<int> Etat_id { get; set; }
        public Nullable<int> TypeEau_id { get; set; }
    
        public virtual Etat Etat { get; set; }
        public virtual TypeEau TypeEau { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelveeEau> RelveeEaux { get; set; }
    }
}
