//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Electricite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Electricite()
        {
            this.RelveeElecs = new HashSet<RelveeElec>();
        }
    
        public int NPolice { get; set; }
        public string Adresse { get; set; }
        public System.DateTime Date { get; set; }
        public string Tel { get; set; }
        public int NCompteur { get; set; }
        public string Reference { get; set; }
        public short Annee { get; set; }
        public Nullable<int> Etat_id { get; set; }
        public Nullable<int> TypeElec_id { get; set; }
    
        public virtual Etat Etat { get; set; }
        public virtual TypeElectricite TypeElectricite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelveeElec> RelveeElecs { get; set; }
    }
}
