//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FacturationEntities : DbContext
    {
        public FacturationEntities()
            : base("name=FacturationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Eau> Eaux { get; set; }
        public virtual DbSet<Electricite> Electricites { get; set; }
        public virtual DbSet<Etat> Etats { get; set; }
        public virtual DbSet<RelveeEau> RelveeEaux { get; set; }
        public virtual DbSet<RelveeElec> RelveeElecs { get; set; }
        public virtual DbSet<TeleCommunication> TeleCommunications { get; set; }
        public virtual DbSet<TypeEau> TypeEaux { get; set; }
        public virtual DbSet<TypeElectricite> TypeElectricites { get; set; }
        public virtual DbSet<TypeTelecommunication> TypeTelecommunications { get; set; }
        public virtual DbSet<RelveeTeleCom> RelveeTeleComs { get; set; }
    }
}
