//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FacturationEntities : DbContext
    {
        public FacturationEntities()
            : base("name=FacturationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Eau> Eaux { get; set; }
        public virtual DbSet<Electricite> Electricites { get; set; }
        public virtual DbSet<Etat> Etats { get; set; }
        public virtual DbSet<RelveeEau> RelveeEaux { get; set; }
        public virtual DbSet<RelveeElec> RelveeElecs { get; set; }
        public virtual DbSet<TeleCommunication> TeleCommunications { get; set; }
        public virtual DbSet<TypeEau> TypeEaux { get; set; }
        public virtual DbSet<TypeElectricite> TypeElectricites { get; set; }
        public virtual DbSet<TypeTelecommunication> TypeTelecommunications { get; set; }
    }
}
