//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturation
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelveeEau
    {
        public int Id { get; set; }
        public short Annee { get; set; }
        public int Trimestre { get; set; }
        public int NIndex { get; set; }
        public int PIndex { get; set; }
        public double NPayer { get; set; }
        public Nullable<int> Eau_NPolice { get; set; }
        public string Eau_Adresse { get; set; }
        public Nullable<System.DateTime> Eau_Date { get; set; }
        public string Eau_Tel { get; set; }
        public Nullable<int> Eau_NCompteur { get; set; }
        public string Eau_Reference { get; set; }
        public string Rapport { get; set; }
    
        public virtual Eau Eau { get; set; }
    }
}
