//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturation
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelveeTeleCom
    {
        public int Id { get; set; }
        public short Mois { get; set; }
        public double NPayer { get; set; }
        public string TeleCom_NPolice { get; set; }
        public string TeleCom_Adresse { get; set; }
        public Nullable<System.DateTime> TeleCom_Date { get; set; }
        public string TeleCom_Tel { get; set; }
        public string TeleCom_MD { get; set; }
        public string TeleCom_Reference { get; set; }
        public string Rapport { get; set; }
    
        public virtual TeleCommunication TeleCommunication { get; set; }
    }
}
