//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturation
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeleCommunication
    {
        public int NPolice { get; set; }
        public string Adresse { get; set; }
        public System.DateTime Date { get; set; }
        public string Tel { get; set; }
        public string MD { get; set; }
        public int Forfait { get; set; }
        public double Montant { get; set; }
        public Nullable<int> Etat_id { get; set; }
        public Nullable<int> TypeTelecom_id { get; set; }
    
        public virtual Etat Etat { get; set; }
        public virtual TypeTelecommunication TypeTelecommunication { get; set; }
    }
}
